version: '2'
services:
  sc:
    build: supercollider-arch
    ports:
      - "2222:22"
    depends_on:
      - front-streamer
  front-streamer:
    build: front-streamer
    ports:
      - "2280:80"
